version: '3'
services:
  starbots-manipulation:
    image: starbots-ros2-manipulation-real
    container_name: starbots-ros2-manipulation-real
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    privileged: true
    networks:
      - starbots-network
    ports:
      - "9090:9090"
    restart: always
    entrypoint: /ros_entrypoint.sh
    command: ["sleep 22 && ros2 launch ur3e_manipulation starbots_delivery_rviz.launch.py & \
      sleep 27 && ros2 launch starbots_webapp start_foxglove.launch.xml"]

volumes:
  logs: {}
networks:
  starbots-network:
    driver: bridge